# Generated by Django 3.2.8 on 2021-11-19 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=500, verbose_name='College Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='College Email')),
                ('phone', models.CharField(max_length=13, unique=True, verbose_name='College Phone')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Last Login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_image', models.ImageField(upload_to='student_img/%y', verbose_name='Student Image')),
                ('student_name', models.CharField(max_length=300, verbose_name='Student Name')),
                ('student_roll', models.PositiveIntegerField(verbose_name='Student Roll No.')),
                ('student_age', models.PositiveIntegerField(verbose_name='Student Age')),
                ('student_div', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=10, verbose_name='Student Division')),
                ('student_add', models.TextField(verbose_name='Student Address')),
                ('student_course', models.CharField(choices=[('BCA', 'BCA'), ('B-Tech', 'B-Tech'), ('Hotel Management', 'Hotel Management'), ('MCA', 'MCA'), ('M-Tech', 'M-Tech'), ('B-Com', 'B-Com')], max_length=200, verbose_name='Student Course Name')),
                ('student_course_year', models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year')], max_length=200, verbose_name='Student Course Year')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=200, verbose_name='Gender')),
                ('student_fees', models.PositiveIntegerField(verbose_name='Student Fees')),
                ('addmission_date', models.DateField(verbose_name='Addmission Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacultiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_image', models.ImageField(upload_to='faculty_img/%y', verbose_name='Faculty Image')),
                ('faculty_name', models.CharField(max_length=300, verbose_name='Faculty Name')),
                ('faculty_age', models.PositiveIntegerField(verbose_name='Faculty Age')),
                ('faculty_add', models.TextField(verbose_name='Faculty Address')),
                ('faculty_teach_in_which_div', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=100, verbose_name='Faculty Teach In Which Div')),
                ('faculty_teach_in_which_class', models.CharField(choices=[('BCA', 'BCA'), ('B-Tech', 'B-Tech'), ('Hotel Management', 'Hotel Management'), ('MCA', 'MCA'), ('M-Tech', 'M-Tech'), ('B-Com', 'B-Com')], max_length=100, verbose_name='Faculty Teach In Which Class')),
                ('faculty_teach_in_which_year', models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year')], max_length=100, verbose_name='Faculty Teach In Which Year Student')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=200, verbose_name='Gender')),
                ('salary', models.PositiveIntegerField(verbose_name='Faculty Salary')),
                ('joined_date', models.DateField(verbose_name='Joined Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='COllegeInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_image', models.ImageField(upload_to='college_img/%y', verbose_name='College Image')),
                ('clg_university_img', models.ImageField(upload_to='university_img/%y', verbose_name='University Image')),
                ('college_address', models.TextField(verbose_name='College Address')),
                ('college_priciple', models.CharField(max_length=300, verbose_name='COllege Principle')),
                ('college_HOD', models.CharField(max_length=300, verbose_name='COllege HOD')),
                ('college_university', models.CharField(max_length=300, verbose_name='College University')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name='Date Upload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
